# Generated by Django 4.1.2 on 2023-01-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_profile_id_alter_user_first_name_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='about_me',
            new_name='department',
        ),
        migrations.AddField(
            model_name='profile',
            name='post',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
