# Generated by Django 4.1.2 on 2023-02-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_rename_about_me_profile_department_profile_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='teaching_courses',
            field=models.JSONField(default={}),
        ),
    ]
