# Generated by Django 4.1.2 on 2023-02-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_profile_teaching_courses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='teaching_courses',
            field=models.JSONField(default=[]),
        ),
    ]
