# Generated by Django 4.1.2 on 2023-02-28 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_profile_teaching_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='course_reviews',
            field=models.IntegerField(default=0),
        ),
    ]
