# Generated by Django 4.1.2 on 2022-10-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0003_paper_approval_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
    ]
