# Generated by Django 2.2.14 on 2022-10-17 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0004_paper_likes_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
