# Generated by Django 2.2.14 on 2022-12-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0011_auto_20221224_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='organised_date',
            field=models.CharField(blank=True, default=models.CharField(blank=True, max_length=250, null=True), max_length=250, null=True),
        ),
    ]
