# Generated by Django 2.2.14 on 2023-01-02 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0012_auto_20221224_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='total_citation',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
