# Generated by Django 4.1.2 on 2023-01-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0013_paper_total_citation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
