# Generated by Django 4.1.2 on 2023-01-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0017_alter_paper_organised_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='total_citation',
            field=models.IntegerField(blank=True, max_length=250, null=True),
        ),
    ]
