# Generated by Django 4.1.2 on 2023-01-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0019_alter_paper_total_citation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='authors',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
