# Generated by Django 4.1.2 on 2023-01-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0021_alter_paper_doi_alter_paper_sjr_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='paper_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
