# Generated by Django 4.1.2 on 2022-11-29 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0006_auto_20221128_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
