# Generated by Django 2.2.14 on 2022-11-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('papers', '0007_alter_paper_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
