# Generated by Django 2.2.14 on 2022-11-30 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20221130_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='default.jpg', height_field=100, null=True, upload_to='profile_pics/', verbose_name='Image', width_field=100),
        ),
    ]
